---
name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 28.2
    - uses: actions/checkout@v3
    - name: Run tests
      run: './run-tests.sh'
  melpazoid:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 28.2
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install
      run: |
        python -m pip install --upgrade pip
        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
        pip install ~/melpazoid
    - name: Run
      env:
        LOCAL_REPO: ${{ github.workspace }}
        RECIPE: (sway-lang-mode :repo "hhamud/sway-mode" :fetcher github)
      run: echo $GITHUB_REF && make -C ~/melpazoid
